### PR TITLE
Added Aternos Thanos image

### PR DESCRIPTION
**Pull request by CristianEduardMihai**
## Added Aternos Thanos image. A utility that allows you to shrink Minecraft worlds by deleting unused chunks. 
https://github.com/CristianEduardMihai/Thanos-Docker

### Why This Is Needed
Covered in the summary

### What Changed
only added

### Added

added /template/apps/thanos-amd64.json
added /images/aternos-thanos.png

### Changed
nothing

### Fixed
nothing

### Removed
nothing

### Screenshots

image
image

## Checklist

- [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
- [x] Does your submission pass tests?
- [x] Have you linted your code locally prior to submission?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you updated documentation, as applicable?1

### CODE REVIEW

**Comment by rmiddle** [comment]
It image points at "image_amd64": "linuxserver/adguardhome-sync:latest", doesn't look right.  Also there isn't an arm section?

**Comment by CristianEduardMihai** [comment]
> It image points at "image_amd64": "linuxserver/adguardhome-sync:latest", doesn't look right. Also there isn't an arm section?

Sorry for that! It was very late when I made that pr and forgot to put in my image.
As for ARM, it only works on arm64. Tried to build the image on my pi 4 and it failed.

**Comment by martadinata666** [comment]
Is this one shot run? Or continous? As by default restart_policy is always, you can change it if you need to.

**Comment by CristianEduardMihai** [comment]
> Is this one shot run? Or continous? As by default restart_policy is always, you can change it if you need to.

It is one shot run. Closes after it finishes optimizing a world.
image
```json
"restart_policy": "never",
```
I have set the restart policy to "never", just as portainer shows. Should I set it to "no"?

**Comment by martadinata666** [comment]
> > Is this one shot run? Or continous? As by default restart_policy is always, you can change it if you need to.
> 
> It is one shot run. Closes after it finishes optimizing a world.
> image
> ```json
> "restart_policy": "never",
> ```
> I have set the restart policy to "never", just as portainer shows. Should I set it to "no"?

Its good then

**Pull request merged**
