### PR TITLE
Adding WordPress Arm32

### PR DESCRIPTION
**Pull request by AlbertoHugonin**
Wordpress stack with mysql database from:

- arm32v7/wordpress
- hypriot/rpi-mysql

Base images where used

It should be noted:

- there are php plugins missing used by very popular plugin like PHP PDO_MYSQL for MailPoet, so they need to be integrated in the img
- ssl cannot seem to work for the moment, but i added the port to the config anyway
- tested WooCommerce and it works, not tried payment though 
- the db and wordpress volume are separated, i think they can be merged
- not so sure what type 3-2-1 means in the .json

This is my first pull request so let me know if i made any mistakes

Cheers

### CODE REVIEW

**Comment by rmiddle** [comment]
Why use arm32v7/wordpress instead of _/wordpress those both support arm32 and look like they are based on the same code base?

**Comment by AlbertoHugonin** [comment]
If i use /wordpress directly it just pulls the arm32v7/wordpress:latest image that is the same if you directly use arm32v7/wordpress.
I thinks it doesn't change much but i will change to /wordpress anyway

**Comment by AlbertoHugonin** [comment]
This is what i changed:

- I managed to get ssl working so i made a document describing the process, English it's not my first language so i am sorry for any mistakes i made. 
- i changed the image to /wordpress
- i removed port ssl variable because it's not important to choose it, portainer does it on it's own

Let me know what you think

**Comment by rmiddle** [comment]
I cleaned up the patch and committed it under https://github.com/novaspirit/pi-hosted/pull/173 .

**Pull request closed without merging**
