### PR TITLE
update install, Update scripts

### PR DESCRIPTION
**Pull request by goldjunge91**
# Summary

i install a fresh pi and can not use the pi-hosted scripts i check for issues #385 make the changes 
and tested for my is everting working fine now.
thx to @jiimint he create issues #385

### Added

#!/bin/sh

error() 
{
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

check_internet() 
{
  printf "Checking if you are online..."
  wget -q --spider http://github.com
  if [ $? -eq 0 ]; then
    echo "Online. Continuing."
  else
    error "Offline. Go connect to the internet then run the script again."
  fi
}
## Fixed

install_docker.sh
install_portainer.sh
update_portainer.sh

## Removed

couple litte syntax errors in the error function

### Warning we automatically generate the following files, your change(s) will overwritten.
* docs/README.md
* template/portainer-v2-arm32.json
* template/portainer-v2-arm64.json
* template/portainer-v2-amd64.json
* tools/README.md
* docs/AppList.md
* docs/DocumentList.md
* pi-hosted_template/template/portainer-v2.json 

## Please make any changes to these files instead 
* template/apps/`some-application-name.json`
* stack/`some-stack-name.yml` 
* docs/`some-docsname.md`
* tools/`some-script.sh`
* build/info.json

### CODE REVIEW

**Comment by jiimint** [comment]
@goldjunge91 Thanks for your quick replay. Have a nice day.

**Comment by goldjunge91** [comment]
> Fresh install raspberry pi OS not including bash right now?

i'm not don't know why you ask this but i'm not a  programmer, but if you wish the files as bash script i can change it have try both and both are working if i understand it correctly that are only the typ of the art processing the script ""#!/bin/bash"" this ""#!/bin/sh"" both give u same error and both work :D  i will uploaded it tomorrow.

**Comment by goldjunge91** [comment]
> @goldjunge91 Thanks for your quick replay. Have a nice day.

lucky that i got annoyed from my raspberry pi' :D its a pain to get home assisstant working with, homebridge, docker, plex and pi hole :D  ( now i try install first home assistant with supervisor + docker for: Plex, Jdownloader, Homebrige, octofarm, grafana, Pihole, 

but starting after my pull request, things  gets going worst with my raspberry so 6 hours later to go decided flashing a new sd card :D 
so good night @all 👯‍♀️

**Comment by martadinata666** [comment]
> > Fresh install raspberry pi OS not including bash right now?
> 
> i'm not don't know why you ask this but i'm not a programmer, but if you wish the files as bash script i can change it have try both and both are working if i understand it correctly that are only the typ of the art processing the script ""#!/bin/bash"" this ""#!/bin/sh"" both give u same error and both work :D i will uploaded it tomorrow.

The change itself resulting error rather than solved it, as i explained at #385 , dont run `sh ./install_portainer.sh` just run `./install_portainer.sh`. Because `sh` and `bash` process scripts differently.

**Comment by goldjunge91** [comment]
i change my fork the files back to bash. and its working.

**Pull request closed without merging**
